Vagrant.configure("2") do |config|
  box_name_debian = "debian/bookworm64" # Debian 12
  # box_name_debian = "debian/bullseye64" # Debian 11

  nodes = {
    "dns01" => {
      ip: "192.168.56.2",
      box_name: box_name_debian,
      cpus: 1, # if not enough, increase to 2
      memory: 512,  # if not enough, increase to 1024
      disksize: 10, # if not enough, increase to 20
      group: "dns",
    },
    # "admin01" => {
    #   ip: "192.168.56.3",
    #   box_name: box_name_debian,
    #   cpus: 2,
    #   memory: 4096,
    #   disksize: 20,
    #   group: "admin",
    # },
  }

  nodes.each do |name, cfg|
    config.vm.define name do |node|
      node.vm.box = cfg[:box_name]
      node.vm.hostname = "#{name}.lab.internal"

      node.vm.network "private_network", ip: cfg[:ip], adapter: 2

      # Resize root disk BEFORE first boot
      # VirtualBox default is 40GB.
      # Requires vagrant-disksize plugin: `vagrant plugin install vagrant-disksize`
      node.disksize.size = "#{cfg[:disksize]}GB"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = cfg[:memory]
        vb.cpus = cfg[:cpus]
        vb.name = name
      end
    end
  end
end