Vagrant.configure("2") do |config|
  box_name_debian = "debian/bookworm64" # Debian 12
  # box_name_debian = "debian/bullseye64" # Debian 11
  box_name_ubuntu = "ubuntu/jammy64" # Ubuntu 22.04

  nodes = {
    "dns01" => {
      ip: "192.168.56.2",
      box_name: box_name_debian,
      cpus: 1, # if not enough, increase to 2
      memory: 512,  # if not enough, increase to 1024
      disksize: 10, # if not enough, increase to 20
      group: "dns",
    },
    # "admin01" => {
    #   ip: "192.168.56.3",
    #   box_name: box_name_debian,
    #   cpus: 2,
    #   memory: 4096,
    #   disksize: 20,
    #   group: "admin",
    # },
    "k3s01-ctrl01" => {
      ip: "192.168.56.11",
      box_name: box_name_ubuntu,
      cpus: 2,
      memory: 4096,
      disksize: 20, # if not enough, increase to 40
      group: "k3s01_servers",
    },
    "k3s01-wrk01" => {
      ip: "192.168.56.12",
      box_name: box_name_ubuntu,
      cpus: 1, # if not enough, increase to 2
      memory: 2048,
      disksize: 20, # if not enough, increase to 40
      group: "k3s01_agents",
    },
    "k3s01-wrk02" => {
      ip: "192.168.56.13",
      box_name: box_name_ubuntu,
      cpus: 1, # if not enough, increase to 2
      memory: 2048,
      disksize: 20, # if not enough, increase to 40
      group: "k3s01_agents",
    },
  }

  # Optional external node files to reduce merge conflicts.
  # Place one file per node in .nodes/ as .rb, .yml, or .yaml.
  # If `name` is omitted, filename (without extension) is used as node name.
  #
  # Ruby file example (.nodes/new_node.rb):
  # {
  #   ip: "192.168.56.22",
  #   box_name: box_name_debian,
  #   cpus: 1,
  #   memory: 512,
  #   disksize: 10,
  #   group: "test"
  # }
  #
  # YAML file example (.nodes/new_node.yaml):
  # ip: 192.168.56.22
  # box_name: box_name_debian
  # cpus: 1
  # memory: 512
  # disksize: 10
  # group: test
  nodes_dir = File.join(__dir__, "_nodes")
  box_aliases = {
    "box_name_debian" => box_name_debian,
    "box_name_ubuntu" => box_name_ubuntu,
    "debian" => box_name_debian,
    "ubuntu" => box_name_ubuntu,
  }

  if Dir.exist?(nodes_dir)
    require "yaml"

    Dir.glob(File.join(nodes_dir, "*.{rb,yml,yaml}")).sort.each do |node_file|
      ext = File.extname(node_file)

      raw_node = case ext
                 when ".rb"
                   # Evaluate in current binding so box_name_debian/box_name_ubuntu can be used.
                   eval(File.read(node_file), binding, node_file)
                 when ".yml", ".yaml"
                   YAML.safe_load(File.read(node_file), aliases: false) || {}
                 else
                   {}
                 end

      unless raw_node.is_a?(Hash)
        raise "Node file #{node_file} must return a Hash"
      end

      node_name = (raw_node[:name] || raw_node["name"] || File.basename(node_file, ext)).to_s
      node_cfg = {}
      raw_node.each do |k, v|
        node_cfg[k.to_sym] = v
      end
      node_cfg.delete(:name)

      if node_cfg[:box_name].is_a?(String) && box_aliases.key?(node_cfg[:box_name])
        node_cfg[:box_name] = box_aliases[node_cfg[:box_name]]
      end

      required_keys = %i[ip box_name cpus memory disksize group]
      missing = required_keys.select { |k| !node_cfg.key?(k) }
      unless missing.empty?
        raise "Node file #{node_file} is missing required keys: #{missing.join(", ")}"
      end

      nodes[node_name] = node_cfg
    end
  end

  nodes.each do |name, cfg|
    config.vm.define name do |node|
      node.vm.box = cfg[:box_name]
      node.vm.hostname = "#{name}.lab.internal"

      node.vm.network "private_network", ip: cfg[:ip], adapter: 2

      # Resize root disk BEFORE first boot
      # VirtualBox default is 40GB.
      # Requires vagrant-disksize plugin: `vagrant plugin install vagrant-disksize`
      node.disksize.size = "#{cfg[:disksize]}GB"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = cfg[:memory]
        vb.cpus = cfg[:cpus]
        vb.name = name
      end
    end
  end
end